const APP_BASE_URL = process.env.APP_BASE_URL || "http://localhost:3000";
const MENU_IMAGE_PATH =
  process.env.MENU_IMAGE_PATH ||
  "C:\\Users\\nk\\.cursor\\projects\\c-Users-nk-OneDrive-Desktop-EntryTest\\assets\\c__Users_nk_AppData_Roaming_Cursor_User_workspaceStorage_afa247f2e4502163fc74db28857b1cff_images_Castea-52ee8401-67f3-45e1-a524-4c0d1e7f85ce.png";

const STAGE = {
  GREETING: "GREETING",
  COLLECTING_ITEM: "COLLECTING_ITEM",
  ASK_ADD_MORE: "ASK_ADD_MORE",
  CONFIRM_ORDER: "CONFIRM_ORDER",
  COLLECT_CUSTOMER_NAME: "COLLECT_CUSTOMER_NAME",
  COLLECT_CUSTOMER_PHONE: "COLLECT_CUSTOMER_PHONE",
  COLLECT_CUSTOMER_ADDRESS: "COLLECT_CUSTOMER_ADDRESS",
  COLLECT_CUSTOMER_NOTE: "COLLECT_CUSTOMER_NOTE",
  COLLECT_PAYMENT: "COLLECT_PAYMENT",
  FINALIZED: "FINALIZED"
};

module.exports = {
  APP_BASE_URL,
  MENU_IMAGE_PATH,
  STAGE
};

