const APP_BASE_URL = process.env.APP_BASE_URL || "http://localhost:3000";

const STAGE = {
  GREETING: "GREETING",
  COLLECTING_ITEM: "COLLECTING_ITEM",
  ASK_ADD_MORE: "ASK_ADD_MORE",
  CONFIRM_ORDER: "CONFIRM_ORDER",
  COLLECT_CUSTOMER_NAME: "COLLECT_CUSTOMER_NAME",
  COLLECT_CUSTOMER_PHONE: "COLLECT_CUSTOMER_PHONE",
  COLLECT_CUSTOMER_ADDRESS: "COLLECT_CUSTOMER_ADDRESS",
  COLLECT_CUSTOMER_NOTE: "COLLECT_CUSTOMER_NOTE",
  COLLECT_PAYMENT: "COLLECT_PAYMENT",
  FINALIZED: "FINALIZED"
};

module.exports = {
  APP_BASE_URL,
  STAGE
};

